
WITH CUSTOMERDATA
(CUSTOMERNAME,CUSTOMERGROUP,PRIMARYCONTACT)
AS
(
SELECT CUSTOMERNAME,CUSTOMERGROUP,PRIMARYCONTACT
FROM CUSTOMERDATA
)
SELECT*
FROM CUSTOMERDATA


WITH CUSTOMERDATA
(CUSTOMERCATEGORYNAME,CITY,PROVINCE)
AS
(
SELECT CUSTOMERCATEGORYNAME,CITY,PROVINCE
FROM CUSTOMERDATA
)
SELECT*
FROM CUSTOMERDATA	

SELECT*
FROM CUSTOMERDATA INNER JOIN CUSTOMERDATA ON CUSTOMERNAME.CUSTOMERGROUP.PRIMARYCONTACT;
	
