  

--THIS IS THE PROCESS TO FOLLOW IF YOUR DOING THE CUSTOMERNAME

-- THIS IS HOW GET THE CUSTOMERNAME IN CUSTOMERDATA IN FULL
SELECT CUSTOMERDATA. CUSTOMERNAME,
SUM (INVOICEDATA.SALES),
SUM (INVOICEDATA.QUANTITY)
FROM INVOICEDATA
JOIN CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CUSTOMERNAME
ORDER BY SUM(INVOICEDATA.SALES) DESC;


--THIS IS HOW TO GET THE CUSTOMERNAME IN CUSTOMERDATA
-- IN SHORT FORM
SELECT C.CUSTOMERNAME,
SUM(I.SALES),
SUM(I.QUANTITY)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CUSTOMERNAME
ORDER BY SUM(I.SALES)DESC;


--THIS IS THE STEPS TO FOLLOW IF YOU ARE TRYING TO GET 
--YOUR CITY TOTAL SALES IN CUSTOMERDATA

--NAME IN FULL FOR CITY
SELECT CUSTOMERDATA.CITY,
SUM(INVOICEDATA.SALES),
SUM(INVOICEDATA.QUANTITY)
FROM INVOICEDATA INVOICEDATA
JOIN CUSTOMERDATA CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CITY
ORDER BY SUM(INVOICEDATA.SALES) DESC;


--NAME IN SHORT FOR CITY
SELECT C.CITY,
SUM(I.SALES),
SUM(I.QUANTITY)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CITY
ORDER BY SUM(I.SALES)DESC;


--THIS IS THE STEPS TO FOLLOW TO 
--GET THE CUSTOMERCATEEGORYNAME IN CUSTOMERDATA

--NAME IN SHORT FOR CUSTOMERCATEGORYNAME
SELECT C.CUSTOMERCATEGORYNAME,
SUM(I.QUANTITY)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CUSTOMERCATEGORYNAME
ORDER BY SUM(I.SALES)DESC;


--NAME IN FULL FOR CUSTOMERCATEGORYNAME
SELECT CUSTOMERDATA.CUSTOMERCATEGORYNAME,
SUM(INVOICEDATA.QUANTITY)
FROM INVOICEDATA INVOICEDATA
JOIN CUSTOMERDATA CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CUSTOMERCATEGORYNAME
ORDER BY SUM(INVOICEDATA.SALES) DESC;


--THIS IS HOW TO GET THE CUSTOMERGROUP 
--IN SHORT FROM CUSTOMERDATA

SELECT C.CUSTOMERGROUP,
SUM(I.SALES)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CUSTOMERGROUP
ORDER BY SUM(I.SALES)DESC;


--THIS IS THE STEPS TO FOLLOW TO GET 
--THE CUSTOMERGROUP FROM CUSTOMERDATA
--THE NAME IN FULL
SELECT CUSTOMERDATA.CUSTOMERGROUP,
SUM(INVOICEDATA.SALES)
FROM INVOICEDATA INVOICEDATA
JOIN CUSTOMERDATA CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CUSTOMERGROUP
ORDER BY SUM(INVOICEDATA.SALES) DESC;


SELECT*
FROM CUSTOMERDATA									   
LIMIT 1O								   
									   




--THIS IS THE PROCESS TO FOLLOW IF YOUR DOING THE CUSTOMERNAME

-- THIS IS HOW GET THE CUSTOMERNAME IN CUSTOMERDATA IN FULL
SELECT CUSTOMERDATA. CUSTOMERNAME,
SUM (INVOICEDATA.SALES),
SUM (INVOICEDATA.QUANTITY)
FROM INVOICEDATA
JOIN CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CUSTOMERNAME
ORDER BY SUM(INVOICEDATA.SALES) DESC;


--THIS IS HOW TO GET THE CUSTOMERNAME IN CUSTOMERDATA
-- IN SHORT FORM
SELECT C.CUSTOMERNAME,
SUM(I.SALES),
SUM(I.QUANTITY)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CUSTOMERNAME
ORDER BY SUM(I.SALES)DESC;


--THIS IS THE STEPS TO FOLLOW IF YOU ARE TRYING TO GET 
--YOUR CITY TOTAL SALES IN CUSTOMERDATA

--NAME IN FULL FOR CITY
SELECT CUSTOMERDATA.CITY,
SUM(INVOICEDATA.SALES),
SUM(INVOICEDATA.QUANTITY)
FROM INVOICEDATA INVOICEDATA
JOIN CUSTOMERDATA CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CITY
ORDER BY SUM(INVOICEDATA.SALES) DESC;


--NAME IN SHORT FOR CITY
SELECT C.CITY,
SUM(I.SALES),
SUM(I.QUANTITY)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CITY
ORDER BY SUM(I.SALES)DESC;


--THIS IS THE STEPS TO FOLLOW TO 
--GET THE CUSTOMERCATEEGORYNAME IN CUSTOMERDATA

--NAME IN SHORT FOR CUSTOMERCATEGORYNAME
SELECT C.CUSTOMERCATEGORYNAME,
SUM(I.QUANTITY)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CUSTOMERCATEGORYNAME
ORDER BY SUM(I.SALES)DESC;


--NAME IN FULL FOR CUSTOMERCATEGORYNAME
SELECT CUSTOMERDATA.CUSTOMERCATEGORYNAME,
SUM(INVOICEDATA.QUANTITY)
FROM INVOICEDATA INVOICEDATA
JOIN CUSTOMERDATA CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CUSTOMERCATEGORYNAME
ORDER BY SUM(INVOICEDATA.SALES) DESC;


--THIS IS HOW TO GET THE CUSTOMERGROUP 
--IN SHORT FROM CUSTOMERDATA

SELECT C.CUSTOMERGROUP,
SUM(I.SALES)
FROM INVOICEDATA I
JOIN CUSTOMERDATA C ON I.CUSTOMERCODE = C.CUSTOMERID
GROUP BY C.CUSTOMERGROUP
ORDER BY SUM(I.SALES)DESC;


--THIS IS THE STEPS TO FOLLOW TO GET 
--THE CUSTOMERGROUP FROM CUSTOMERDATA
--THE NAME IN FULL
SELECT CUSTOMERDATA.CUSTOMERGROUP,
SUM(INVOICEDATA.SALES)
FROM INVOICEDATA INVOICEDATA
JOIN CUSTOMERDATA CUSTOMERDATA ON INVOICEDATA.CUSTOMERCODE = CUSTOMERDATA.CUSTOMERID
GROUP BY CUSTOMERDATA.CUSTOMERGROUP
ORDER BY SUM(INVOICEDATA.SALES) DESC;


SELECT*
FROM CUSTOMERDATA									   
LIMIT 1O								   
									   
									   

WITH CUSTOMERDATA
(CUSTOMERNAME,CUSTOMERGROUP,PRIMARYCONTACT)
AS
(
SELECT CUSTOMERNAME,CUSTOMERGROUP,PRIMARYCONTACT
FROM CUSTOMERDATA
)
SELECT*
FROM CUSTOMERDATA


WITH CUSTOMERDATA
(CUSTOMERCATEGORYNAME,CITY,PROVINCE)
AS
(
SELECT CUSTOMERCATEGORYNAME,CITY,PROVINCE
FROM CUSTOMERDATA
)
SELECT*
FROM CUSTOMERDATA	

SELECT*
FROM CUSTOMERDATA INNER JOIN CUSTOMERDATA ON CUSTOMERNAME.CUSTOMERGROUP.PRIMARYCONTACT;
										   






































									   